name: 'Web'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APP
        run: flutter build web --release --web-renderer canvaskit

      - name: Push to Github Pages
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "hymnus.ponces.xyz" > CNAME
          git init
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add origin https://${{ secrets.GH_TOKEN }}@github.com/ponces/hymnus.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin gh-pages --force
        working-directory: build/web
